// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'megaMenu.d.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'megaMenu.d.g.dart';

@freezed
class MenuCategory with _$MenuCategory {
  const factory MenuCategory(
      {required String title,
      required List<SubMenuCategory> children}) = _MenuCategory;

  factory MenuCategory.fromJson(Map<String, Object?> json) =>
      _$MenuCategoryFromJson(json);
}

@freezed
class SubMenuCategory with _$SubMenuCategory {
  const factory SubMenuCategory(
      {required String title,
      required List<MenuItem> children}) = _SubMenuCategory;

  factory SubMenuCategory.fromJson(Map<String, Object?> json) =>
      _$SubMenuCategoryFromJson(json);
}

@freezed
class MenuItem with _$MenuItem {
  const factory MenuItem({
    required String item,
  }) = _MenuItem;
  factory MenuItem.fromJson(Map<String, Object?> json) =>
      _$MenuItemFromJson(json);
}
